---
abstract: 'Moose-like sugar for Class::Tiny'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::Fatal: 0.003
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 0
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.007, CPAN::Meta::Converter version 2.120921'
keywords: []
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Class-Tiny-Antlers
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
provides:
  Class::Tiny::Antlers:
    file: lib/Class/Tiny/Antlers.pm
    version: 0.020
requires:
  Class::Tiny: 0.005
  Role::Tiny: 1.000000
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/Class-Tiny-Antlers/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Class-Tiny-Antlers
  homepage: https://metacpan.org/release/Class-Tiny-Antlers
  license: http://dev.perl.org/licenses/
  repository: https://github.com/tobyink/p5-class-tiny-antlers
version: 0.020
x_provides_scripts: {}
