---
abstract: 'Moose-like sugar for Class::Tiny'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::Fatal: '0.003'
  Test::More: '0.96'
  Test::Requires: '0.06'
configure_requires:
  ExtUtils::MakeMaker: '6.17'
dynamic_config: 0
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.023, CPAN::Meta::Converter version 2.140640'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Class-Tiny-Antlers
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  Class::Tiny::Antlers:
    file: lib/Class/Tiny/Antlers.pm
    version: '0.023'
requires:
  Class::Tiny: '0.006'
  perl: '5.006'
resources:
  IRC: irc://irc.perl.org/#moops
  Identifier: http://purl.org/NET/cpan-uri/dist/Class-Tiny-Antlers/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Class-Tiny-Antlers
  homepage: https://metacpan.org/release/Class-Tiny-Antlers
  license: http://dev.perl.org/licenses/
  repository: git://github.com/tobyink/p5-class-tiny-antlers.git
version: '0.023'
